### ISSUE TITLE
Structure and best practices

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-node#100]
Based on the discussion regarding nest.js/express/sails i'll suggest a few small changes in structure. Others are welcomed to do the same in the comments. 

Practices:
- root folder starts with lower case  eg: "models"
- subfolders start with upper case eg: "Auth"
- we use typescript, thus => PascalCase
- all folders have a `index.ts` file where we export everything from that folder

Structure:
- `@types`: types required by typescript for various libs/components etc. ex `Typesense.ts`
- `controllers`: controller logic for all the routes, ex: `controllers/Provider/index.ts` with a `downloadFile()` function
- `models`: actual models/classes/interfaces that we need from a business perspective ex: `OceanNode`, `DDO`, etc.
- `services`: business logic, database stuff, etc.
- `routes`: we link the routes with the controller ex: `router.post('/downloadFile, ProviderController.downloadFile);`
- `helpers` or `utils`: generic functions that are reused in multiple places. If a function is used just in a service, it should be there not in here
- `middleware`: not sure if we need this, we could put here the auth logic when we will have it

p2p should be in `services` or be standalone somewhere else
I did not take in consideration the "jobs" required by the indexer, there should be another folder where we define those. Same pattern as `routes`, one place we just define them and then link them to the appropriate controller/service

`helpers/scripts/clientExample.ts` should not be there, it should be another folder `scripts` in root, same level as `src`

**Comment by AnaLoznianu** [comment]
@alexcos20 feels different about this. Let's discuss it when you get back
