### ISSUE TITLE
Storage: fileinfo

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#105]
fileInfo command will return info about a certain file.
It has the following purposes:
- allow users to observe details about a file (type, length, name, type of storage)
- allow platforms to prevent orders if file is not accessible
- allow multiple parties to compute checksums (used in c2d flows)

Command description:
- for published assets
```json
{
command: "fileInfo",
node: "NodeB ID", // optional, use only that node
did: "did:op:123",
serviceId: "123",
fileIndex: "0"  // optional, narrow results to a single file,
checksum: true // optional, compute sha256 checksum of file if required
}
```
- for new assets
```json
{
command: "fileInfo",
node: "NodeB ID", // optional, use only that node
file:  { ... fileObject ... }
checksum: true // optional, compute sha256 checksum of file if required
}
```

Returns an array of objects (for each file):
```json
[
    {
        "valid": true,   (if url is accesible, ipfs cid exists, etc.  If yes, next fields are populated)
        "contentLength":"1161",
        "contentType":"application/json",
        "name": if available & secure
        "type":  [url, ipfs, arweave, etc]
        "checksumType":  "sha256",
        "checksum": ".."
    },...
]
```

Implementation:
 - extend storage class with fileInfo function (each storage type might have it's own implementation)
  - implement core command
  - expose on http
  
  References:
   - file object:  https://docs.oceanprotocol.com/developers/storage
   - existing provider implementation:  https://github.com/oceanprotocol/provider/blob/main/ocean_provider/routes/consume.py#L95

**Comment by AnaLoznianu** [comment]
@alexcos20 Can you please add more info to this story?
