### ISSUE TITLE
Handle Encrypted DDOs

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/ocean-node#108]
- if encrypted, reach out to provider/node that was used to encrypt and fetch decrypted ddo
 
Reference:  https://github.com/oceanprotocol/aquarius/blob/main/aquarius/events/decryptor.py

**Comment by AnaLoznianu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/108?planning-poker) with Zenhub @alexcos20 @an7e @bogdanfazakas @jamiehewitt15 @mariacarmina @paulo-ocean
