### ISSUE TITLE
Enhance OceanNode class

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean-node#136]
Enhance OceanNode class to remove `setOceanNode` function and replace with a function that does the instanting all in one function.

Tried approaches:

- builder pattern
- put inside constructor code

Both of them failed due to mocha, not running the tests and receiving `ERROR: null`.

Follow up from https://github.com/oceanprotocol/ocean-node/pull/122#discussion_r1409278955

Maybe change the Database constructor since it is the one that throws the error in mocha testing.

**Comment by paulo-ocean** [comment]
This class need a big refactor.
we definitely need to have a singleton when running the node. and we should be able to instantiate the class from "outside" as many times as possible, without relying on the singleton as well.
All the handlers and config should refer to the specific node instance (and encapsulated inside)
Right now, the config is outside of the class and everytime it tries to read the same info from process.env vars..

**Comment by paulo-ocean** [comment]
closed on https://github.com/oceanprotocol/ocean-node/pull/175
will create a new issue once the Handler classes are done and incorporate them
