### ISSUE TITLE
Fee Token defaults

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#142]
Right now, owner must define FEE_TOKEN in order to start the node.

Let's have some defaults:
 - if FEE_AMOUNT is not defined, make it 0
 - if FEE_TOKEN is not defined, make it equal to OCEAN address per each chain
 
 This will ease onboarding for non tech users

**Comment by paulo-ocean** [comment]
closed on https://github.com/oceanprotocol/ocean-node/pull/151
