### ISSUE TITLE
MetadataCreated & MetadataUpdated additional checks

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/ocean-node#156]
- [ ] Checking if the NFT is deployed by our factory
- [ ] Checking the metadata proofs
- [ ] Checking if we have the same txid with the "old" asset
- [ ] Checking the block number (transaction block for MetadataUpdated to be greater than the "old" asset.event.block)

**Comment by mariacarmina** [comment]
> Checking the metadata proofs

This one is not mandatory for this task, as @alexcos20 mentioned in Slack, there is a seprate issue for integrating the proofs. Metadata proofs cannot be retrieved from the event itself (such as MetadataCreated or MetadataUpdated). 
All being said, the rest of the checks remain valid.
