### ISSUE TITLE
Indexer - Advertise DID for content routing, when we store a DDO

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#168]
**Is your feature request related to a problem? Please describe.**
When we are indexing/storing a DDO, we are not advertising it to the network

**Describe the solution you'd like**
When we store it, we need to tell the other peers we are providing that ddo

**Describe alternatives you've considered**

**Additional context**
Related to worker thread
```
worker.on('message', (event: any) => {
        if (event.method === 'store-last-indexed-block') {
          this.updateLastIndexedBlockNumber(event.network, event.data)
        }
        if (
          event.method === EVENTS.METADATA_CREATED ||
          event.method === EVENTS.METADATA_UPDATED ||
          event.method === EVENTS.METADATA_STATE
        ) {
          this.createOrUpdateDDO(event.network, event.data, event.method)
        }
      })
```
At least when we respond to METADATA_CREATED we need to advertise it.. (right now, we are just storing it on DB)
Other states will eventually require a more advanced check

**Comment by paulo-ocean** [comment]
also update findProviders(cid) with a big timeout (right now is just 5 secs)

**Comment by alexcos20** [comment]
we also need to investigate what happends after 24 hours  (when dht entry expires), but most likely  that will be another issue

**Comment by paulo-ocean** [comment]
> we also need to investigate what happends after 24 hours (when dht entry expires), but most likely that will be another issue

yep. worst case scenario i would say each node wpuld probably have to re-advertise to others.. all the stuff he has locally, again..

**Comment by paulo-ocean** [comment]
closed on https://github.com/oceanprotocol/ocean-node/pull/186
