### ISSUE TITLE
Make DB config optional

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#173]
Now, is mandatory to have a database connection
But we might have use cases which does not require indexer&provider, so let's make it optional.
If it's not set, we should set hasIndexer=false, to disable it and disable the provider part as well

Use cases:
 - circuit relay for p2p
 - node  for car UI   (will not store anything, just forward commands to another nodes)

**Comment by jamiehewitt15** [comment]
This is done in: https://github.com/oceanprotocol/ocean-node/pull/182
