### ISSUE TITLE
All Loggers should log to the same transports

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#196]
Right now when we create a new Logger instance, we can decide which transport to use.
As a result, some loggers are just logging to the console, others to the console and DB, etc..
It should not be up to the developer to choose where to log..
Logger transports should be configurable, as they are already, but it needs some extra refactoring so we don't have to choose the transport every time we create a new instance (so a little less freedom than current setup).
For instance;
We can have different log levels logging to different transports (ex: Info goes only to console, Error to db and console, etc)
Or we can also have some transports for development, others for production

**Comment by alexcos20** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/196?planning-poker) with Zenhub @an7e @bogdanfazakas @jamiehewitt15 @paulo-ocean

**Comment by alexcos20** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/196?planning-poker) with Zenhub @mariacarmina

**Comment by paulo-ocean** [comment]
closed on https://github.com/oceanprotocol/ocean-node/pull/218[https://github.com/oceanprotocol/ocean-node/pull/218](url)
