### ISSUE TITLE
DDO Schema handling

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#205]
Once we have validateDDO command:
- when adding new ddo (Metadata created), identify the right collection and store the ddo  (indexer)
- when query, make sure all collections are used

**Comment by jamiehewitt15** [comment]
We also need to ensure that a did does not exist in more than one collection, so if a ddo is updated to use a new schema it should be removed from all other schemas.

**Comment by alexcos20** [comment]
so the flow is the following:
- metaDataCreated/Update 
    - check version. If we don't have a version in the DDO, discard it (we cannot validate it)
    - if valid, put it in corresponding collection, otherwise log error and discard it
    - when updated, and new_version != current_version, delete it from old collection and put updated version in new collection
- metaDataState:
    - if changes from active to disabled:  delete it from old collection and put short version in "short_collection" collection
    - if changes from disabled to active:  delete it from "short_collection" and put it in corresponding collection according to version


When doing query:
use all "version" collections + "short_collection"

**Comment by jamiehewitt15** [comment]
Merged in: https://github.com/oceanprotocol/ocean-node/pull/239
