### ISSUE TITLE
Indexer: purgatory

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#213]
Given two ENV vars that control lists of assets and accounts, indexer should prevent ingesting assets which are a match

Format of the lists: https://github.com/oceanprotocol/list-purgatory

**Comment by paulo-ocean** [comment]
will close after fix of [https://github.com/oceanprotocol/ocean-node/issues/275](https://github.com/oceanprotocol/ocean-node/issues/275)
