### ISSUE TITLE
C2D: add C2D_CLUSTERS env for ocean-node 

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#226]
Compared to provider, which only supports one C2D Cluster,  ocean-node will handle multiple ones

So, enhance our config to take an additional C2D_CLUSTERS config env.
Our config should look like:
```json
{
...
"c2dClusters": [
{ 
  url: "http:///...",
  hash: "0x123'
}
]
```

where hash  = sha256(url)

 C2D_CLUSTER env:
If it's a string -> there is only one cluster
If it's an array -> we have several clusters

**Comment by paulo-ocean** [comment]
hi @alexcos20 , i'm wondering if isn't it better to just have this var as an array..
```
If it's a string -> there is only one cluster
If it's an array -> we have several clusters
```
I think its a lot simpler to just have an array, of clusters, either with 1 or multiple values
what do you think?
thkx

**Comment by alexcos20** [comment]
I'm concern about people habits.  Old provider takes one env that looks like:
```
OPERATOR_SERVICE_URL = 'http://operator.url.myexample.com'
```

But if it's simpler, then let's go with an array
