### ISSUE TITLE
Improve integration tests

### ISSUE THREAD

**Issue by bogdanfazakas** [oceanprotocol/ocean-node#250]
- [ ] get rid of the delays and delay method
- [x] add env var for indexer refresh period and make it lower for integration tests (around 5s)
- [ ] find a replacement for waitToIndex()
- [ ] maybe concatenate some of the flows and reuse parts of the logic
... to be extended

**Comment by paulo-ocean** [comment]
for the delays, timeouts,  maybe its worth try emit / listen events instead,  to trigger notifications for certain actions, instead of relying on pooling mechanisms

**Comment by paulo-ocean** [comment]
will take care of this one too

**Comment by jamiehewitt15** [comment]
We should also look out for any try / catches that are used in the tests and might hide issues or failed requests. These can lead to the tests passing with just an error being logged, without the test itself failing. For example, the start order test in `src/test/integration/completeFlow.test.ts`:

```
  it('should start an order', async function () {
    this.timeout(15000) // Extend default Mocha test timeout
    try {

         ...

    } catch (error) {
      console.log(error)
    }
  })
```

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/267](url)
