### ISSUE TITLE
Storage:  missing checksums

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#253]
When https://github.com/oceanprotocol/ocean-node/issues/105 was defined,  the requirements were to add checksum as well.

By looking in the code while debugging something with Ilia, we discovered that there is no checksum for files.

So, let's implement in the following way:

- define an ENV  "MAX_CHECKSUM_LENGTH ": define the maximum length for a file if checksum is required. If file size is greater, we do not compute checksum.  Default value: 10 Mb
- update function storage.getFileInfo  to take extra parameter:  forceChecksum (default false)
- update function storage.getFileInfo  and underlying storage classes to add checksum to output:
    - if ( forceChecksum==false and filesize=<MAX_CHECKSUM_LENGTH) || (forceChecksum ) -> compute hash
    - else  do not compute hash

In this way, we can have checksums for datasets only if they are smaller than a predefined size, but always compute checksums for algos

**Comment by paulo-ocean** [comment]
this was closed as part of [https://github.com/oceanprotocol/ocean-node/pull/254](url)
