### ISSUE TITLE
Short DDO validation & remove hardcoded validation

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean-node#256]
We are using the `validateObject` function to validate DDOs. However, it is currently doing this validation without checking what fields are required by the schema. So for example, the short DDO is unable to pass the validation as there are hardcoded checks for `@context` and `metadata`. The validation should only check for fields that are required by the schema. This could also cause problems for other DDO formats from other organisations, or ones added by us in the future.

```Typescript

export async function validateObject(
  obj: Record<string, any>,
  chainId: number,
  nftAddress: string
): Promise<[boolean, Record<string, string>]> {
  CORE_LOGGER.logMessage(`Validating object: ` + JSON.stringify(obj), true)
  const extraErrors: Record<string, string> = {}
  if (!('@context' in obj)) {
    extraErrors['@context'] = 'Context is missing.'
  }
  if ('@context' in obj && !Array.isArray(obj['@context'])) {
    extraErrors['@context'] = 'Context is not an array.'
  }
  if (!('metadata' in obj)) {
    extraErrors.metadata = 'Metadata is missing or invalid.'
  }
  ;['created', 'updated'].forEach((attr) => {
    if ('metadata' in obj && attr in obj.metadata && !isIsoFormat(obj.metadata[attr])) {
      extraErrors.metadata = `${attr} is not in ISO format.`
    }
  })

  if (!chainId) {
    extraErrors.chainId = 'chainId is missing or invalid.'
  }

...
```

**Comment by mariacarmina** [comment]
Also remove the metadata checks, there are handled by shacl schemas

**Comment by mihaisc** [comment]
@mihaisc figure out if we need SHACL or we can replace it with some other validation schema
