### ISSUE TITLE
HTTP Endpoint:  encryptFile

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#265]
Sometimes, data must be encrypted before being stored.  
Think about encrypting DDOs for enterprise, or encrypting files before uploading to public storages like IPFS
So, we need to implement encrypt file HTTP Endpoint  (not to be confused with #40)

There are two ways of encrypting a file:

1. Sending the file object.
     - Content-type header must be set to application/json
     - Body contains file object
     - Query.encryptMethod can be aes or ecies (if missing, defaults to aes)
 

2. Sending the raw content
     - Content-type header must be set to application/octet
     - Body contains raw file content (can be huge)
     - Query.encryptMethod can be aes or ecies (if missing, defaults to aes)

3. TBD:  Should support  content-type: multipart as well ?

For all cases, we need to return:
 - Body:  encrypted file content
 - Headers  (so caller knows how to construct his files object for publish the asset)
     - X-Encrypted-By:  our_node_id
     - X-Encrypted-Method: aes or ecies

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/281](url)
