### ISSUE TITLE
DB:  Investigate rxdb

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#287]
When running ocean-noce, you need one external dependency:  typesense.   

Let's investigate https://rxdb.info/quickstart.html

Advantages : same process, no more multiple docker images.
Might even be better overall

TO DO:

- [ ] investigate if all req are meet
- [ ] add it to ocean-node
- [ ] do some performance tests

**Comment by alexcos20** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/287?planning-poker) with Zenhub @bogdanfazakas @jamiehewitt15 @mariacarmina @paulo-ocean

**Comment by paulo-ocean** [comment]
I don't think there is any good alternative here.
All more "popular" projects on the same category are not that popular at all, not much activity, poorly maintained or outdated, few downloads, just one or two devs, etc.. 
For instance, these 2 are the next in line:
https://www.npmjs.com/package/tyrdb
https://www.npmjs.com/package/nosql-json-database
I'm not sure about any

**Comment by alexcos20** [comment]
all plugins are paid, no need to go further
