### ISSUE TITLE
BE:  Authentication function

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#288]
Some actions on the dashboard will required admin privileges.
Let's build the base for that

- [ ] research how to do the signature.   Proposal:
      - Users signs a message that looks like   String(nonce + '-' + expiryTimestamp)
      - For every request, users adds:
           - nonce
           - expiryTimestamp
           - signature
 - [ ] define env var:  ALLOWED_ADMINS,  it can be a string or array of strings
 - [ ] implement function to check auth for admins

**Comment by alexcos20** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/288?planning-poker) with Zenhub @bogdanfazakas @jamiehewitt15 @mariacarmina @paulo-ocean

**Comment by jamiehewitt15** [comment]
Couple of things I'll add on this: 

1. The HTTP endpoint only needs to respond `true` or `false` as I will send another signature from the front end when we call one of the endpoints that requires user authentication. Those other endpoints can then reverify the signature.
2. For the implementation we can follow [the approach that we took in the uploader ](https://github.com/oceanprotocol/uploader_filecoin/blob/74d08f75dd6146c8c66539adb18469def3611103/src/api/upload/upload.service.js#L20)and update it to use ethers 6 and typescrpt.
3. We don't need to check a nonce if we are including an `expiryTimestamp` we just need to verify that the signature has come from an admin account and that it hasn't expired. 

So the implementation would be like this: 

```
const message = expiryTimestamp
const signerAddress = utils.verifyMessage(message, signature).toLowerCase();

if (signerAddress === adminAddress && currentTimestamp < expiryTimestamp){
return true
}
```

**Comment by mariacarmina** [comment]
Thank you for clarifying @jamiehewitt15. Btw how do you prefer to send the `nonce` and `expiryTimestamp` as types? numbers or strings?

**Comment by jamiehewitt15** [comment]
The `expiryTimestamp` would be sent as a number in unix timestamp format. And then if we agree the nonce isn't needed, I won't send it.

**Comment by jamiehewitt15** [comment]
Had a chat with @alexcos20 about this and we agreed on the following: 

1. No need for an HTTP endpoint for authenticating the user. We will just have an HTTP endpoint that returns the public addresses of the admins. 
2. The validation function as described above is still needed as it will be used by the other endpoints e.g. the endpoint for stopping the node. 
3. No need for a nonce, we can just check the `expiryTimestamp` to check that the message is still valid.

**Comment by mariacarmina** [comment]
> And then if we agree the nonce isn't needed, I won't send it.

I thought we would use nonce for signature, it's another security measure.
