### ISSUE TITLE
Add endpoint to export indexing queue

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#289]
This will be used by the dashboard to display the current indexing queue

**Comment by paulo-ocean** [comment]
Right now there is only a "re-index" queue, which is used when explicitly we want to re-index some did
we are indexing as soon as we processed the events from the network.. should we have other queue, or we are just referring to reindex queue here?
thanks

**Comment by mihaisc** [comment]
Nope, that is the one, the re-index queue, basically we want to display in the dashboard that queue

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/304](url)
