### ISSUE TITLE
BE: Allow admin to stop node

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#292]
Expose an endpoint for admin that will stop the node  (process.exit), after doing necessary cleanups.

When node is started with something like pm2  or docker using restart:always, this will behave like a forced restart.

Of course, admin needs to auth itself

**Comment by alexcos20** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/292?planning-poker) with Zenhub @bogdanfazakas @jamiehewitt15 @mariacarmina @paulo-ocean

**Comment by mariacarmina** [comment]
For the moment, what are the specific cleanups? the database, indexer? do we have those type of methods in the current codebase?
