### ISSUE TITLE
BE: Endpoint to allow admin to transfer collected fees

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#294]
Ocean-node will collect fees  for different services (download, compute, etc).
Create an endpoint that will allow the admin to transfer those fees.

Input params:
 - token address  (if 0x0 = native token for that chain)
 - chainId
 - token amount
 - destination address

**Comment by mihaisc** [comment]
This is refering to provider fees on the node. The node is making a tx to the desired wallet
