### ISSUE TITLE
Authenticate admin

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#296]
Some actions on the dashboard will required admin privileges.
Let's build the base for that in the UI.   Depends on #288

TO DO:

- [ ] prepare signature function. Message = String(nonce + '-' + expiryTimestamp)
- [ ] store expiryTimestamp,nonce and signature to browser localdb
- [ ] send expiryTimestamp,nonce and signature whenever is needed for auth calls

TBD: expiryTimestamp should be hardcoded (ie:  valid for next 24h) or allow user to define?

**Comment by alexcos20** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/296?planning-poker) with Zenhub @bogdanfazakas @jamiehewitt15 @mariacarmina @paulo-ocean

**Comment by jamiehewitt15** [comment]
> TBD: expiryTimestamp should be hardcoded (ie: valid for next 24h) or allow user to define?

It will be more secure if we hardcode it to a short time, rather than letting the user sign a 5 year expiring time which introduces a security risk.
