### ISSUE TITLE
Security:   Command input parameter validation

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#306]
Right now, we are doing validation of command's input parameters in http endpoints section.

But, a P2P command sent by a malicious node is handled  by the handlers, without any type of validation

Task:
 - move all validation from http endpoints section to handlers section.  Each handler should have it's own validation
 - http endpoints:  try to pass null if a params is missing, handlers should handle that, don't do any kind of validation, as it's redundant

**Comment by alexcos20** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/306?planning-poker) with Zenhub @bogdanfazakas @jamiehewitt15 @mariacarmina @paulo-ocean

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/324](url)
