### ISSUE TITLE
Write performance/load tests

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-node#311]
We will use k6 for performance/load tests, it will be hosted locally in our infrastructure.

1. Research what k6 can do and figure out what we could easily implement. We want to test things like cpu/ram usage, response times, network usage, how many requests can the enpoints handle etc.
2. Propose a list of test with a rough estimation for each
3. Write tests

**Comment by paulo-ocean** [comment]
hi @alexcos20 do we have an env for this? i believe so
in any case i think its a good idea if i also install this locally so i can start playing with it
Should i create a folder on the nodes test/ directory for k6 list of tests + scripts?
Let me know how we want to proceed on this
thanks

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/484](https://github.com/oceanprotocol/ocean-node/pull/484)
