### ISSUE TITLE
Command:  status

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#32]
This exposes node details , like nodeId and publicKey/eth address

TO DO:

- [ ]  implement core function status
- [ ]   expose it on http interface
- [ ]   expose it on p2p interface

Command Description:

```
{
command: "status",
node: "NodeB ID", // optional, if missing, it refers to current node
}
```

Response JSON: 
```
{
"id": "1234",
"publicKey": "0x123",
"address": "0x123",
"version": "v1.0",
"http" : true/false,
"p2p": true/false,
"provider": [
     {
        "chainId" : "5123",
        "network": "polygon",
     },
    { 
        "chainId" : "53",
        "network": "eth",
    }
],
"indexer": 
 [
    {
        "chainId" : "5123",
        "network": "polygon",
        "block":"123"
    },
    { 
        "chainId" : "53",
        "network": "eth",
        "block":"123"
    }
  ]
}
```

**Comment by AnaLoznianu** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/32?planning-poker) with Zenhub @mariacarmina
