### ISSUE TITLE
Node crashes when response status !== 200

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#335]
This one was under the wood for a long time :-)
Its on the sink function that reads and streams the commands responses. 
The node crashes when the status response is !== 200 (mostly on specific errors, without a stream response, cause that´s where we usually use other status codes). 
If its 200 then its fine
It basically tries to write more bytes after closing the stream
ERR_STREAM_WRITE_AFTER_END

**Comment by jamiehewitt15** [comment]
Yeah, I'm getting the same thing. I think we should increase the priority of this one. 

For example, send a body with an invalid or missing parameter and then the node crashes: 

```
{
  component: 'CORE',
  moduleName: 'CORE',
  level: 'info',
  message: 'Command validation failed: {"valid":false,"status":400,"reason":"Missing one ( \\"expiryTimestamp\\" ) or more required field(s) for command: \\"stopNode\\". Required fields: expiryTimestamp,signature"}',
  timestamp: '2024-03-20 16:41:11'
}

```

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/337](url)
