### ISSUE TITLE
Should we use the swagger file for API docs?

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#343]
Right now we have the following lines on index:
```
 app.use(
    '/docs',
    swaggerUi.serve,
    swaggerUi.setup(undefined, {
      swaggerOptions: {
        url: '/swagger.json'
      }
    })
  )
```
but we are not using it all, and the page shows nothing.. 
We are just writing .md files, like README.md, API.md, env.md
should we write swagger docs from API.md  for instance?

**Comment by alexcos20** [comment]
Let's see if there is a nice way of having both HTTP and P2P commands documented.
If not, we will stick to .md files

**Comment by paulo-ocean** [comment]
well, its probably is not worth the effort after all.. 
i had a lot of issues just trying to configure it and i'm not exactly sure how to document all without a big amount of work
probably better to stick with .md files and remove the swagger references and dependencies anyway
