### ISSUE TITLE
FindDDO Handler:  validate nft address & chainId

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#346]
In findDDO, we get a list of DDOs from remote nodes.  But what if one of those nodes is malicious?

Let's validate that ddo:
 - make sure that ddo.id  = sha256(nftAddress+chainId)
 - maker sure that we have rpc connection for that chain. otherwise, reject it, because we have no way of checking the ddo
 - make sure nftAddress exists
 - make sure that ddo.event is real, by checking all fields
 
```json
      "event": {
          "tx": "0x8cae47b24eedb7e9ed5c7501119fd32f4646b6b04702e82382fabdf2257aac74",
         "block": 39322263,
         "from": "0xEB18BaD7365a40E36A41fB8734eB0B855d13b74F",
         "contract": "0x08d2eF7c255834dBB7513e8b3E744D05748a7079",
         "datetime": "2023-02-15T13:51:01"
  }
  ```

       - is tx real? does it contains a MetaDataCreated or Updated ?
       - is block no true?
       - etc..
  - check ddo hash
  - if DDO passes validation, and we have indexer on, insert it in our database as well

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/363](url)
