### ISSUE TITLE
replace getDDO with findDDO

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#348]
Right now, there are a lot of getDDO calls all over the code.
But if that asset is not indexed, or node has no index capabilities, a lot of requests will fail (imagine a download call).

So, let's refactor:
 - make sure findDDO searches local database first, then remote
 - if findDDO finds a newer version of the ddo, it should update our database
 - add a flag force to findDDO function (if that is set to TRUE, it will force a remote search, no matter what is stored in our node)
 - add force flag to p2p command and http endpoint
 - see if we need to refactor code so we can always pass did (string) or DDOs as arguments for all functions dealing with ddos, in order to reduce number of calls for findDDO

**Comment by bogdanfazakas** [comment]
closed by #417
