### ISSUE TITLE
Security: Order transactions

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#351]
Ocean-node hardcodes startOrder events in a tx, and it only takes the 1st one

(see https://github.com/oceanprotocol/ocean-node/blob/develop/src/components/core/utils/validateOrders.ts#L98)

scenario: you can create a smart contracts with 2 orders and 2 order started events in the same transaction, and then you can consume the 2nd asset while paying for the 1st one, which of course, is much cheaper or even free, created by attacker

Let's check contract address, payer, consumer, then retrieve the right eventIndex and extract the correct event

**Comment by bogdanfazakas** [comment]
closed by #370
