### ISSUE TITLE
Security:  Incorect validation of file structure

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#353]
User publishes expensive asset, I (as malicious user) want access to that dataset, copy encrypted files string into my own ddo -> then I create a dispenser, reach out to ocean node and I want to download the same asset for free. 

Let's fix this by validating nftAddress and datatokenAddress in file object after decryption

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/383](url)
