### ISSUE TITLE
Indexer:   Fix chunk reading

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#354]
In indexer code, chunk size is always hardcoded.

Move https://github.com/oceanprotocol/ocean-node/blob/develop/src/components/Indexer/crawlerThread.ts#L79 before while on process blocks.
If an RPC call will fail we need to reduce the chunk size, if chunk size is less than 1, make it 1
RPC call success and we do reduce the chunk size -> go back to original quota (reset the chunk size to the original size for the moment)

**Comment by bogdanfazakas** [comment]
closed bt #389
