### ISSUE TITLE
Fix 'state' endpoint

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#356]
'State' command is implemented in a wrong manner, doing something else than it should. 
Let's fix it.

Purpose:
 - have a history for each did, identifying if the asset was successful indexed or we had some errors

Examples:
 - did with errors: https://v4.aquarius.oceanprotocol.com/api/aquarius/state/ddo?did=did:op:38fa9341749d1628a86d782013d1b6bb2fbd7aafe07be97cf96985d9829f8e59
 - successful did:  https://v4.aquarius.oceanprotocol.com/api/aquarius/state/ddo?did=did:op:fa0e8fa9550e8eb13392d6eeb9ba9f8111801b332c8d2345b350b3bc66b379d5

Definition of output (some changes compared to Aquarius)
  - chainId  - chain id of the asset
  - did  = id of the asset
  - nft = nft address
  - txId = last tx that created/updated metadata
  - valid = if schema was valid  (we might have cases when ddo is published on chain, but it's validation against the schema fails
  - error = text describing the error (maybe validation, maybe decrypt, maybe remote provider error, etc)

**Comment by bogdanfazakas** [comment]
closed by #375
