### ISSUE TITLE
Node can get stuck processing the same "faulty" block forever

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#366]
For some context: 

my node was out of sync, it was missing the transactions for the last couple of months, most likely because i had to prune docker images and restart from scratch (so new DB as well)

There were assets published  at a time that we, were not not doing any checks on the flags for encryption, or dealing with encryption/decryption at all, but right now on the Indexer/processor we check for the flags and try to decrypt or decompress the DDOs accordingly..

So, if we start indexing from an older block, now the checks in place do not match the data published and we end up having errors for some events.

**But, The main problem:**
- whenever we fail to process some events on a specific block, the node continues to try to process the same block, over and over... this leads to the same errors and at the end the node is just stuck on a loop, trying to process events for the same block that keep failing...

This part is inside the while(true) loop:
```
const networkHeight = await getNetworkHeight(provider)

    const startBlock =
      lastIndexedBlock && lastIndexedBlock > deployedBlock
        ? lastIndexedBlock 
        : deployedBlock
```
So, if any error happens here, it will always  call `processBlocks()` again with the same `startBlock` on the following iterations. Reducing the chunkSize does not help because we always start from the same place

**The proposed solution:**
-  We need to make sure that whenever we catch errors on some events for some block, we have to skip that block (or those events) and move forward. Maybe we can try the reindex queue, but we can't retry forever the same start block

This is particularly important when we bootstrap a new node, or when we want to reindex the entire chain (or some specific transaction). The node MUST not be stuck on a faulty block/event

PS: my node was stuck at block **`5390003`**

**Comment by bogdanfazakas** [comment]
closed by #389
