### ISSUE TITLE
There is a failing integration test regarding ddo state

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#388]
After the changes done for "state ddo" database, we have a test that  fails
"`should store the ddo state in the db with no errors and retrieve it using did`"
there is something wrong there, maybe a timeout or something, might worth a look

**Comment by paulo-ocean** [comment]
this is still an issue, i'm reopening... the test keeps passing or failing randomly

**Comment by bogdanfazakas** [comment]
closed by #389
