### ISSUE TITLE
Command:  encrypt

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#39]
Implement encrypt command.

- [ ]  implement core function encrypt
- [ ]  expose it on http interface
- [ ]  expose it on p2p interface

Command description:

{
  command: "encrypt",
  node: "NodeB ID",  // optional, if missing, it refers to current node
  blob: "http://example.com",
  encoding:   [ String | Base58] // what type of encoding is used
  encryptionType:   [AES, ECIES] // type of encryption required. optional, defaults to ECIES
 }

**Comment by AnaLoznianu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/39?planning-poker) with Zenhub @an7e @bogdanfazakas @jamiehewitt15 @mariacarmina @paulo-ocean
