### ISSUE TITLE
Bug in download integration test

### ISSUE THREAD

**Issue by FilipMasar** [oceanprotocol/ocean-node#401]
**Describe the bug**
There is a bug in `/integration/download.test.ts`. [Here](https://github.com/oceanprotocol/ocean-node/blob/develop/src/test/integration/download.test.ts#L288) it is missing await. That whole `it` block is not doing what it should.

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/403](url)
