### ISSUE TITLE
MetadataEventProcessor should add `nft` field to the ddo when saving in db

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean-node#404]
MetadataEventProcessor should add `nft` field to the ddo when saving in db. Right now we add only nftAddress, did, chainId https://github.com/oceanprotocol/ocean-node/blob/develop/src/components/Indexer/processor.ts#L310.
`nft` field should be build in MetadataEventProcessor as well.

**Comment by bogdanfazakas** [comment]
but do we really need to have this in the ocean node MetadataEventProcessor process event? 
When i went through current aquarius  codebase i have not seen this logic there, and also in our current publish flows Ocean Market for eg we do the nft object there see https://github.com/oceanprotocol/market/blob/main/src/%40utils/nft.ts#L49 .
I've seen the question from enterpise team but i think the proper response there would have been that the one publishing is reponsible for adding the `NFT` in the `DDO` .

**Comment by mariacarmina** [comment]
+ did overwrite as well in indexer.
