### ISSUE TITLE
Use the batch_size parameter to control the number of documents.

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean-node#406]
Use the batch_size parameter to control the number of documents.
A larger value will speed up deletions, but will impact performance.
see when deleting all ddos from db with filter_by on chainId https://github.com/oceanprotocol/ocean-node/pull/332/files/28745f334c4a8cf4b6a5ef45998706cd7ee4d823#diff-a5b385b3226d31be17cd0f7df9a6a311b96ff62dc505120225fbcbd57d8a86ddR74

**Comment by bogdanfazakas** [comment]
done in #421
