### ISSUE TITLE
Command:  detailedStatus

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#41]
This exposes all node details & capabilities , like 
  - nodeId and publicKey/eth address
  - supported type of storages
  - supported schemas for DDO
  - C2D attached clusters
  - etc

TO DO:

- [ ]  implement core function extendedInfo
- [ ]   expose it on http interface
- [ ]   expose it on p2p interface

Command description:

{
command: "extendedInfo",
node: "NodeID", // optional, if missing, it refers to current node
}

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/395](url)
