### ISSUE TITLE
Disk usage

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#410]
While debugging some gh runners, I saw this:

![Screenshot 2024-04-30 091851](https://github.com/oceanprotocol/ocean-node/assets/7489447/20512a95-a245-4a49-9b6b-8233b986397e)

we have 2GB in ocean-node folder, which is a lot.
This will also lead to huge docker files..

Can we optimize any of it?  Dashboard > 1.2Gb seems a lot

**Comment by jamiehewitt15** [comment]
Yeah, I'll have a look at optimising the dashboard
