### ISSUE TITLE
Status command works only if DB_URL is exported

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean-node#433]
Status command works only if DB_URL is exported, we should be able to see the status without indexer not receive 500 Internal Server Error

**Comment by paulo-ocean** [comment]
line 32 should be removed
`const { indexer: indexerDatabase } = oceanNode.getDatabase()`

**Comment by mariacarmina** [comment]
indexer database should be moved in if block with hasIndexer is true
