### ISSUE TITLE
Indexer:  index MetadataCreated event

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#44]
Every time a new metadata is created, we need to store that ddo.

Event source:  https://github.com/oceanprotocol/contracts/blob/main/contracts/templates/ERC721Template.sol#L47C5-L55C28

```
event MetadataCreated(
        address indexed createdBy,
        uint8 state,
        string decryptorUrl,
        bytes flags,
        bytes data,
        bytes32 metaDataHash,
        uint256 timestamp,
        uint256 blockNumber)
```

This means the following:
 - get data, and detect if it's encrypted or not
 - store it

**Comment by AnaLoznianu** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/44?planning-poker) with Zenhub @bogdanfazakas
