### ISSUE TITLE
Command:  validateDDO

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#47]
We need to validate DDOs before that are published:

TO DO:

- [x]  implement core function validateDDO, according to available schacl schemas
- [ ]   expose it on http interface
- [x]   expose it on p2p interface

Command description:

{
command: "validateDDO",
node: "NodeB ID", // optional, if missing, it refers to current node
ddo: Object,
}

Returns:
 - signed proof of validation
 ```
{
    "hash": "0x"  // ddo hash
    "nodeID": nodeID that signed the proof
    "v" :  signature.v,
    "r" :  signature.r,
    "s" :  signature.s
}

**Comment by mariacarmina** [comment]
It's done in #210

**Comment by jamiehewitt15** [comment]
> - [ ] expose it on http interface

@mariacarmina That hasn't been done in #210

**Comment by mariacarmina** [comment]
@alexcos20 should it be a separate endpoint or integrated in /directCommand along with `findDDO` and `getDDO`?
