### ISSUE TITLE
Command:  getDDO

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#49]
TO DO:

- [ ]  implement core function getDDO (details below)
- [ ]   expose it on http interface
- [ ]   expose it on p2p interface (see below)

Command description:
```json
{
command: "getDDI",
node: "NodeB ID", // optional, use only that node
id: "did:op:123",
}
```

Scenario:
 - DDO already exists on the receiving node.  Then we just serve it

**Comment by AnaLoznianu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/49?planning-poker) with Zenhub @mihaisc @paulo-ocean

**Comment by AnaLoznianu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/49?planning-poker) with Zenhub @an7e @bogdanfazakas @jamiehewitt15 @mariacarmina
