### ISSUE TITLE
Auto-generated key not being added to .env and keys not being deleted when specified when running env set-up from scripts folder

### ISSUE THREAD

**Issue by ChristianCasazza** [oceanprotocol/ocean-node#513]
**Describe the bug**

**To Reproduce**
1. Cd into scripts folder
2. Run the script ./setupNodeEnv.sh 
3. Select create PK, associate wallet with admin, and delete generated out files during script run

**Expected behavior**
The created env file should have the created Pk in the env file and wallet in admin folder, but it doesn't. It also doesn't delete the .out files, which are being placed in the scripts folder

**Desktop (please complete the following information):**
Windows WSL w/ Ubuntu Distro

**Additional context**
The problem only occurs when running the script after cding into the scripts folder. When running from root with the full relative path to the script, it works as expected

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/515](https://github.com/oceanprotocol/ocean-node/pull/515)
