### ISSUE TITLE
Improve GET computeEnvironments response

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean-node#519]
When requesting `computeEnvironments` it should give a valid response even if there are no compute environments, an empty array would be a better response. Currently, I'm receiving a 500 response from this endpoint. 

![image](https://github.com/oceanprotocol/ocean-node/assets/20739535/bb0ba546-b3c6-42b5-a1c2-674a79274633)

**Comment by paulo-ocean** [comment]
btw, you should be getting a 404 if there are no environments, a 500 means something else was wrong

**Comment by jamiehewitt15** [comment]
@paulo-ocean I think you're right. I haven't been able to recreate this so closing it now
