### ISSUE TITLE
Command: decryptDDO

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#53]
Implement deencryptDDO command  (used by other nodes when indexing)

TO DO:

- [ ]  implement core function decryptDDO (with access control)
- [ ]  expose it on http interface
- [ ]  expose it on p2p interface

Command description:

{
command: "decryptDDO",
node: "NodeB ID", // optional, if missing, it refers to current node
decrypterAddress,
chainId,
transactionId,
dataNftAddress,
encryptedDocument,
flags.
documentHash,
nonce,
signature
}

**Comment by AnaLoznianu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/53?planning-poker) with Zenhub @mariacarmina @paulo-ocean @an7e @bogdanfazakas @jamiehewitt15

**Comment by alexcos20** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/53?planning-poker) with Zenhub @an7e @bogdanfazakas @jamiehewitt15 @mariacarmina @paulo-ocean
