### ISSUE TITLE
UI Issue when indexer is not running

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean-node#624]
We have an ugly UI Issue when the indexer is not running:

![image](https://github.com/user-attachments/assets/b18be90e-e48b-4e94-82fc-f61cb59a7bbc)

**Comment by paulo-ocean** [comment]
is this valid? What browser?
tried Opera, Brave and Firefox and i see the alert box as always.
IMO, this looks more like a cache issue or something
![Screenshot from 2024-08-29 10-04-58](https://github.com/user-attachments/assets/ba9bed94-35c6-49eb-a8b4-85917fe2ebbd)

**Comment by bogdanfazakas** [comment]
on some nodes i started lately not visible any more, maybe an issue with dashboard not properly updating, see OPF nodes for reference running 0.1.0 but all new nodes seem to load fine, it was an issue with inline style loading that i ve fixed few days ago before release, maybe something as @paulo-ocean  suggested with cache 
but the actual issue think can be close.

<img width="1813" alt="Screenshot 2024-08-29 at 12 37 37" src="https://github.com/user-attachments/assets/b7d1cc45-3ffd-457c-b761-3304ef6b095d">

**Comment by paulo-ocean** [comment]
ok, closing this one ...
