### ISSUE TITLE
Node http up IP

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-node#629]
<img width="1659" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ebeb5742521d23391414cbfe6d4503ef5f096d5/image.png" alt="image.png" />

Where do we get this IP from? It's not ok

**Comment by paulo-ocean** [comment]
can't see the attached image, but we get ips from public API: '['https://api.ipify.org?format=json'](https://api.ipify.org?format=json)'
if available
