### ISSUE TITLE
WalletConnect authentication

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/ocean-node#63]
The node has in its config the admin address. For the front end to connect to the node and make changes, it needs to connect with the same address the node is configured with. Otherwise, the connection should not be allowed

**Comment by jamiehewitt15** [comment]
Not sure what this issue is about? Whoever is running the node can use the same address in their wallet and the node conifg without any problems, that would already work with metamask, wallet connect etc. We also don't have any endpoints that require this authentication at the moment.
