### ISSUE TITLE
Quick node install script

### ISSUE THREAD

**Issue by g7AzaZLO** [oceanprotocol/ocean-node#638]
As discussed in discord, here attached. I suggest adding the script of automatic node loading and installation to the documentation. . The script installs the docker, Install NodeJS & NPM, download and insntall Typesense, create an .env file with user data and run the docker container 

. <(wget -qO- https://raw.githubusercontent.com/g7AzaZLO/ocean_protocol_auto_installer/main/ocean_install.sh)

**Comment by jamiehewitt15** [comment]
Please put your suggested changes into a pull request so that they can be reviewed.
