### ISSUE TITLE
Step-by-step installation guide. 

### ISSUE THREAD

**Issue by yuriiss** [oceanprotocol/ocean-node#639]
Hello OP Team. As discussed in discord, here is the step-by-step installation guide, which is 100% works. Suggesting to add this guide to official docs as users still straggling with original docker composer guide.

[OP-node installation guide.md](https://github.com/user-attachments/files/16697619/OP-node.installation.guide.md)

**Comment by jamiehewitt15** [comment]
Can you open a pull request with these suggested changes added to the docs folder, and then we can give you feedback on it.

**Comment by RumoursGR** [comment]
I followed the instructions precisely, and both containers work properly now.

This is my ID: 16Uiu2HAmKiGADfHoYHTbArQTvgPWfM2G1vYMY13Kcvd3ojZQXfVa.

But according to nodes.oceanprotocol.com, my node still won't pass the eligibility check. The eligibility issue is Cannot connect to peer(connection error 85.72.158.245:9000: connect EHOSTUNREACH 85.72.158.245:9000).

Any idea how to proceed?
