### ISSUE TITLE
Node crash

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-node#644]
node crashed with error `error: Unable to process P2P command: stream reset` 
Nothing worked after that (HTTP calls or P2P calls)

**Comment by paulo-ocean** [comment]
i can take this one, i suspect i know the issue

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/659](https://github.com/oceanprotocol/ocean-node/pull/659)
