### ISSUE TITLE
Retrieve and display connected nodes

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/ocean-node#65]
Display the list of the nodes connected and also display the public status of a connected node.

Note: Each node has an IP address. We can use it to identify the geographical localization of the node. We can display them all on a map

**Comment by mihaisc** [comment]
currently we can get just a list of ids

`[
    "16Uiu2HAkwWe6BFQXZWg6zE9X7ExynvXEe9BRTR5Wn3udNs7JpUDx",
    "16Uiu2HAkyqdMojcJGsyUJpNLRbwVPT9ZWK63qmY2dy58zwi5obhH"
]`

**Comment by jamiehewitt15** [comment]
Yeah for now this task is just: 

1. call the `/getOceanPeers` endpoint
2. Show a list of the node IDs that this node is connected to

No geographical map or anything like that.

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/339](url)
