### ISSUE TITLE
Download logs

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/ocean-node#66]
- [ ] give the ability to download the available logs from the connected node
- [ ] don't display the logs, just give the option to download them

**Comment by jamiehewitt15** [comment]
> give the ability to download the available logs from the connected node

Not sure exactly what you mean by this, we already have the ability to download the logs via the API endpoint (https://github.com/oceanprotocol/ocean-node/issues/69). Is this issue about downloading the logs via a dashboard or something else?

**Comment by AnaLoznianu** [comment]
It's the interface that should expose the functionality you implemented 👍
