### ISSUE TITLE
Easy onboarding in the quickstart for infura RPCs

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean-node#663]
We can add a couple of questions to the quickstart script:

```
Do you have an Infura API key? [y/n]
Provide your Infura API key:
```

And then we can generate the RPCs env for them using their infura key.

**Comment by mihaisc** [comment]
ask for urls, not infura key

**Comment by mihaisc** [comment]
ask for urls, not infura key
