### ISSUE TITLE
Node dashboard 

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-node#665]
We need a full refresh

Current info
- node id - OK
- address - OK
- connected nodes : total OK, list not very usefull
- HTTP IP : get it from p2p announce address?
- indexer, indexing queue - ?????
- SUPPORTED Networks - OK
- SUPPORTED STORAGE - OK
- Admin Accounts - OK
- PLATFORM - OK
- display node configuration ( env vars, without sensitive data), maybe the ability to download it (without sensitive information)

**Comment by paulo-ocean** [comment]
"indexer, indexing queue - ?????"
That's the indexing tasks currently on queue (for reindex transactions)

**Comment by mihaisc** [comment]
The "????" were, do we need it, is it valuable there, but I gues it should be
