### ISSUE TITLE
ValidateDDO fails because DDO shacl Schemas are missing 'credentials' (introduced at service level)

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#709]
We updated the `Service` definition to include a `credentials` object
but we haven't updated the shacl schemas with the corresponding definition of `CredentialsShape`
so the `validateObject()` function fails
ref:
[https://github.com/oceanprotocol/ocean-node/commit/c5799f9d187851922a9e80a090e0e19325a06aa9](https://github.com/oceanprotocol/ocean-node/commit/c5799f9d187851922a9e80a090e0e19325a06aa9)

**Comment by mihaisc** [comment]
@paulo-ocean status?
