### ISSUE TITLE
If RPCS and INDEXER_NETWORKS are not aligned we should show a log message 

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#728]
`INDEXER_NETWORKS` takes precedence over `RPCS`...
if the INDEXER_NETWORKS contains a different chain than the ones defined on RPCS (or if the chains from RPCS are not present on INDEXER_NETWORKS)
It does not index anything, but there are no logs or anything warning about the .env mismatch..
at least a warning message would be nice, since the 2 .env vars if present, need to be aligned...
This can generate some confusion

**Comment by paulo-ocean** [comment]
additionally, this message should also be a warning, not an error:
2024-10-22T17:42:41.685Z error: CONFIG: ❌ Missing or Invalid INDEXER_NETWORKS env variable format,running Indexer with all supported networks defined in RPCS env variable ...
INDEXER_NETWORKS is NOT mandatory, and if we have RPCS its enough, so it should be a WARN and most, not an ERROR

**Comment by jamiehewitt15** [comment]
> additionally, this message should also be a warning, not an error: `2024-10-22T17:42:41.685Z error: CONFIG: ❌ Missing or Invalid INDEXER_NETWORKS env variable format,running Indexer with all supported networks defined in RPCS env variable ...` INDEXER_NETWORKS is NOT mandatory, and if we have RPCS its enough, so it should be a WARN at most, not an ERROR

Yeah, makes sense
