### ISSUE TITLE
C2D: Delete storage for Free Compute

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#737]
In addition to #735 , we need to delete all storage occupied by a free job (both output storage & db record) when the results of a free job are downloaded successfully (do not wait for storageExpiry to kick in)

**Comment by paulo-ocean** [comment]
included on PR [https://github.com/oceanprotocol/ocean-node/pull/705](https://github.com/oceanprotocol/ocean-node/pull/705)
