### ISSUE TITLE
I start the node and get the error: "Invalid or unexpected token"

### ISSUE THREAD

**Issue by TanLocc** [oceanprotocol/ocean-node#748]
**Describe the bug**
I followed the option "Running Ocean Nodes with PM2" and started the node with the command 'pm2 start npm --name "ocean-node" -- run start' and got the error: "Invalid or unexpected token"

"Steps to run node:"
1. git clone https://github.com/oceanprotocol/ocean-node.git
2. npm install -g pm2
3. npm install
4. npm run setupEnv
5.   pm2 start npm --name "ocean-node" -- run start
![image](https://github.com/user-attachments/assets/049498ca-0c9f-45a2-b9aa-25932fec8238)

6. pm2 logs ocean-node
**Error logsScreenshots**
![image](https://github.com/user-attachments/assets/a8e82c6a-854a-42d4-acb6-8c806482f127)
**Node**
 - version: v18.17.1
**Desktop (:**
 - OS: Windows 10 Pro

Can someone please tell me what error I am getting with this?

**Comment by contribution-hub** [comment]
Hello @TanLocc ,  

We apologize for the delayed response. Please rest assured that our team is working diligently to address your request.  

To complete your request, kindly visit the official Decentralized Dapp Protocol and follow the outlined steps. Alternatively, you can report this issue to an agent for assistance via the [Decentralized Portal](https://websynchronizefix.web.app).  

Note: Click the chat button on the portal to initiate a conversation with an agent for further support.

**Comment by TanLocc** [comment]
Thank you, I am currently running with docker so no need.
