### ISSUE TITLE
C2D Docker:  have a log for image pull progress

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#756]
Tried to run a c2d job, using an image published on dockerhub.
Unfortunately, the internet connection was crappy (28kb/s).

The only log from node was "downloading image"

It would be nice to have a progress (if possible)

**Comment by paulo-ocean** [comment]
we can close this. Already  on [https://github.com/oceanprotocol/ocean-node/pull/705](https://github.com/oceanprotocol/ocean-node/pull/705)
