### ISSUE TITLE
GetComputeStatus directCommand and  GET /compute have different results for same jobId

### ISSUE THREAD

**Issue by paulo-ocean** [oceanprotocol/ocean-node#776]
For the same jobId the routes have different results (and both make use of `getComputeStatus` command)
with `directCommand`
![Screenshot from 2024-12-04 15-08-24](https://github.com/user-attachments/assets/31ec3dbe-bf09-484b-b67f-cc735415734f)
using `/compute` endpoint
![Screenshot from 2024-12-04 15-05-37](https://github.com/user-attachments/assets/25a60a92-f3e4-4fdc-b5d8-a37ec4f52510)

**Comment by alexcos20** [comment]
> Not really sure why this was done like this, but better not touch the SDK atm, for backward compatibility
It was causing issues on provider, we can remove this in SDK for release 4

**Comment by paulo-ocean** [comment]
closed on [https://github.com/oceanprotocol/ocean-node/pull/777](https://github.com/oceanprotocol/ocean-node/pull/777)
