### ISSUE TITLE
Ocean-node fees

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#84]
For certain actions, ocean-node must take some fees.  (IE:  If you want to download 1MB file, you need to pay 1 Ocean , in addition to the asset cost).   This functionality incentives users to run their own Ocean-Nodes

Consume flow looks like :
 - user wants to download asset A , for service 1
 - user calls getFee endpoint, to get ocean-node fees for downloading
 - user pays fees + asset price
- user contacts ocean-node:  here is the txID (contains both asset price + ocean-node fee) , give me the file

TO DO:
- [x]  update config to get the following envs:
           -  FEE_TOKENS = json list, containing fee token address per chain.  Example:  { "1": 0x123, "56": 0x456 }
           -  FEE_AMOUNT = fee amount, per megabyte
 - [x]  create a core function calculateFee(ddo,serviceId)
            - this will use fileInfo command to get the length of the file
            - will analyze the DDO and get validity, so we can know who many times/until then user can download this asset
            - compute required cost using FEE_AMOUNT and FEE_TOKENS
- [x]  create core function createFee (see below)
- [x]  create core function checkFee (see below)
- [x]  create core function getFee
- [x]  expose getFee endpoint in http
- [x]  expose getFee endpoint in libp2p

createFee function:
  - uses calculateFee to compute the fee
  - uses the following flow to create the fee structure:
  
```
     provider_data =  {
            "environment": compute_env,  //  null for us now
            "timestamp": datetime.now(timezone.utc).timestamp(),
            "dt": service.datatoken_address,
            "id": service.id,
        }
    
    message_hash = Web3.solidityKeccak(
        ["bytes", "address", "address", "uint256", "uint256"],
        [
            Web3.toHex(Web3.toBytes(text=provider_data)),
            Web3.toChecksumAddress(provider_fee_address),
            Web3.toChecksumAddress(provider_fee_token),
            provider_fee_amount,
            valid_until,
        ],
    )

    pk = keys.PrivateKey(provider_wallet.key)
    prefix = "\x19Ethereum Signed Message:\n32"
    signable_hash = Web3.solidityKeccak(
        ["bytes", "bytes"], [Web3.toBytes(text=prefix), Web3.toBytes(message_hash)]
    )
    signed = keys.ecdsa_sign(message_hash=signable_hash, private_key=pk)

    provider_fee = {
        "providerFeeAddress": provider_fee_address,
        "providerFeeToken": provider_fee_token,
        "providerFeeAmount": provider_fee_amount,
        "providerData": Web3.toHex(Web3.toBytes(text=provider_data)),
        # make it compatible with last openzepellin https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1622
        "v": (signed.v + 27) if signed.v <= 1 else signed.v,
        "r": Web3.toHex(Web3.toBytes(signed.r).rjust(32, b"\0")),
        "s": Web3.toHex(Web3.toBytes(signed.s).rjust(32, b"\0")),
        "validUntil": valid_until,
    }
```

checkFee function:       given a txID, checks:
  - the address that signed the fee signature = ocean-node address
  - amount, tokens, etc are a match
  

smart contract implementation:
 - https://github.com/oceanprotocol/contracts/blob/main/contracts/templates/ERC20Template.sol#L65-L74
 - https://github.com/oceanprotocol/contracts/blob/main/contracts/templates/ERC20Template.sol#L447-L508
 - https://github.com/oceanprotocol/contracts/blob/main/contracts/templates/ERC20Template.sol#L522
 - https://github.com/oceanprotocol/contracts/blob/main/contracts/templates/ERC20Template.sol#L589-L608

**Comment by paulo-ocean** [comment]
hi @alexcos20 
couple of questions here:
regarding the calculateFee()
```
"
- this will use fileInfo command to get the length of the file
- will analyze the DDO and get validity, so we can know who many times/until then user can download this asset
- compute required cost using FEE_AMOUNT and FEE_TOKENS
"
```

Afaik, the fileInfo is not implemented yet, so as far as i understood, this part will "mocked" for now, right ? 
Right now, to have something, i'm just replying with the fee structure here.. basically i call createFee() and reply that back

Regarding this part:
```
"
checkFee function: given a txID, checks:

the address that signed the fee signature = ocean-node address
amount, tokens, etc are a match
"
```
As far as i understood, we check the txId (the signature) to see if the siger address == provider/node address
But what is the "message" that was signed? We need that for the "verifyMessage", is it the original fee structure from createFee() ? . will it be passed as param to the function as well?
Right now i have something like
```
export async function checkFee(
  txId: string,
  message: string | Uint8Array // the message that was signed (fee structure) ?
): Promise<boolean> {
  // checkFee function: given a txID, checks:
  // the address that signed the fee signature = ocean-node address
  // amount, tokens, etc are a match
  const nodeAddress = getProviderWalletAddress()
  return await verifyMessage(message, nodeAddress, txId)
}
```
Is the assumption on "message" param correct?

You mention this => "here is the txID (contains both asset price + ocean-node fee)"
How can we get the info from the txID, isn't that just an hash? Maybe i'm missing something here..

Thanks in advance

**Comment by paulo-ocean** [comment]
closed one https://github.com/oceanprotocol/ocean-node/pull/139
