### ISSUE TITLE
Check on-chain order

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-node#88]
When an user want to download an asset, he/she must sent the txid proving that payment using datatoken was done.

That transaction can have two events:
 - OrderStarted   - when a payment was made, using new provider fees
 - OrderReused - whan an order was still valid, but provider fees were expired

We must validate tx send by user by:
 - checking if user is who it claims to be
 - check if datatoken belongs to nft
 - check if datatoken belongs to service
 - check if order is still valid
  - if user tx has OrderReused, fetch tx that contains OrderStarted
  

Reference:  https://github.com/oceanprotocol/contracts/blob/main/contracts/templates/ERC20Template.sol#L82-L97

**Comment by AnaLoznianu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/ocean-node/88?planning-poker) with Zenhub @an7e @bogdanfazakas @jamiehewitt15 @mariacarmina @paulo-ocean @alexcos20
